CREATE TABLE email_copy (
  id                    uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  email_key             text        NOT NULL UNIQUE,
  subject               text        NOT NULL,
  body                  text        NOT NULL DEFAULT '',
  preheader             text        NOT NULL DEFAULT '',
  required_placeholders text[]      NOT NULL DEFAULT '{}',
  body_in_code          boolean     NOT NULL DEFAULT false,
  notes                 text,
  updated_at            timestamptz NOT NULL DEFAULT now()
);

INSERT INTO email_copy (email_key, subject, body, preheader, required_placeholders, body_in_code) VALUES

('welcome_new_user',
'Welcome to CallMagnet — your dashboard is ready',
'<p style="color:#FFFFFF;">Hi {{BUSINESS_NAME}}, your account is ready.</p><p style="color:#FFFFFF;">Email: {{EMAIL}}<br>Password: {{PASSWORD}}</p><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:24px 0;"><tr><td align="center"><a href="{{DASHBOARD_URL}}" style="display:inline-block;background:#06D6A0;color:#000;padding:14px 32px;border-radius:8px;font-weight:700;text-decoration:none;font-size:15px;">Go to my dashboard →</a></td></tr></table>',
'Your CallMagnet dashboard is ready — log in now',
ARRAY['BUSINESS_NAME','EMAIL','PASSWORD','DASHBOARD_URL'],
false),

('welcome_existing_user',
'Welcome to CallMagnet — your dashboard is ready',
'<p style="color:#FFFFFF;">Hi {{BUSINESS_NAME}}, your account is ready. Use your existing password to log in.</p><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:24px 0;"><tr><td align="center"><a href="{{DASHBOARD_URL}}" style="display:inline-block;background:#06D6A0;color:#000;padding:14px 32px;border-radius:8px;font-weight:700;text-decoration:none;font-size:15px;">Go to my dashboard →</a></td></tr></table>',
'Your CallMagnet dashboard is ready — log in now',
ARRAY['BUSINESS_NAME','DASHBOARD_URL'],
false),

('payment_received',
'Payment received — we''re setting up your account',
'<p style="color:#FFFFFF;">Hi {{BUSINESS_NAME}}, payment of ${{AMOUNT}} AUD received. We are setting up your account now.</p>',
'Payment received — we are setting up your account',
ARRAY['BUSINESS_NAME','AMOUNT'],
false),

('you_are_live',
'You''re live',
'<p style="color:#FFFFFF;">Hi {{BUSINESS_NAME}}, your CallMagnet system is active.</p><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:24px 0;"><tr><td align="center"><a href="{{DASHBOARD_URL}}" style="display:inline-block;background:#06D6A0;color:#000;padding:14px 32px;border-radius:8px;font-weight:700;text-decoration:none;font-size:15px;">View your dashboard →</a></td></tr></table>',
'Your CallMagnet system is live',
ARRAY['BUSINESS_NAME','DASHBOARD_URL'],
false),

('day_14',
'Two weeks in, {{BUSINESS_NAME}}.',
'<p style="color:#FFFFFF;">Hi {{BUSINESS_NAME}}, two weeks in — {{SMS_COUNT}} missed calls captured.</p><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:24px 0;"><tr><td align="center"><a href="{{DASHBOARD_URL}}" style="display:inline-block;background:#06D6A0;color:#000;padding:14px 32px;border-radius:8px;font-weight:700;text-decoration:none;font-size:15px;">View your dashboard →</a></td></tr></table>',
'Two weeks of CallMagnet',
ARRAY['BUSINESS_NAME','SMS_COUNT','DASHBOARD_URL'],
false),

('day_30',
'Your first month, {{BUSINESS_NAME}}.',
'<p style="color:#FFFFFF;">Hi {{BUSINESS_NAME}}, one month in — {{SMS_COUNT}} missed calls captured.</p><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:24px 0;"><tr><td align="center"><a href="{{DASHBOARD_URL}}" style="display:inline-block;background:#06D6A0;color:#000;padding:14px 32px;border-radius:8px;font-weight:700;text-decoration:none;font-size:15px;">View your dashboard →</a></td></tr></table>',
'Your first month with CallMagnet',
ARRAY['BUSINESS_NAME','SMS_COUNT','DASHBOARD_URL'],
false),

('farewell',
'Thanks for being a CallMagnet client',
'<p style="color:#FFFFFF;">Hi {{BUSINESS_NAME}}, your subscription has ended. Thank you for being with us.</p>',
'Your CallMagnet subscription has ended',
ARRAY['BUSINESS_NAME','TOTAL_SMS','DELIVERED_SMS','BOOKINGS','DAYS_AS_CLIENT','JOINED_LABEL'],
false),

('expiry_warning',
'Your CallMagnet free period ends soon',
'<p style="color:#FFFFFF;">Hi {{BUSINESS_NAME}}, your free period ends on {{END_DATE}}.</p>',
'Your free period is ending soon',
ARRAY['BUSINESS_NAME','END_DATE'],
false),

('account_live',
'Your CallMagnet account is now live',
'<p style="color:#FFFFFF;">Hi {{BUSINESS_NAME}}, your account is live.</p><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:24px 0;"><tr><td align="center"><a href="{{DASHBOARD_URL}}" style="display:inline-block;background:#06D6A0;color:#000;padding:14px 32px;border-radius:8px;font-weight:700;text-decoration:none;font-size:15px;">Go to dashboard →</a></td></tr></table>',
'Your CallMagnet account is live',
ARRAY['BUSINESS_NAME','DASHBOARD_URL'],
false),

('login_link',
'Your CallMagnet login link',
'<p style="color:#FFFFFF;">Tap the button below to log in. This link expires in 24 hours.</p><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:24px 0;"><tr><td align="center"><a href="{{DASHBOARD_URL}}" style="display:inline-block;background:#06D6A0;color:#000;padding:14px 32px;border-radius:8px;font-weight:700;text-decoration:none;font-size:15px;">Log in to CallMagnet →</a></td></tr></table>',
'Tap to log in to CallMagnet — link expires in 24 hours',
ARRAY['DASHBOARD_URL'],
false),

('daily_summary_active',
'{{WEEK_LABEL}}: {{MISSED_CALLS}} {{MISSED_CALLS_PLURAL}} captured',
'',
'Your CallMagnet daily summary',
ARRAY[]::text[],
true),

('daily_summary_quiet',
'Quiet day — no missed calls captured',
'',
'Your CallMagnet daily summary',
ARRAY[]::text[],
true),

('weekly_summary',
'Your week with CallMagnet — {{WEEK_LABEL}}',
'',
'Your CallMagnet weekly summary',
ARRAY[]::text[],
true),

('monthly_recap',
'Your {{MONTH}} with CallMagnet',
'',
'Your CallMagnet monthly recap',
ARRAY[]::text[],
true),

('button_tap_restaurant',
'🍽️ Table request received',
'',
'A customer tapped a button on your Middle Man page',
ARRAY[]::text[],
true),

('button_tap_barber',
'💇 Booking request received',
'',
'A customer tapped a button on your Middle Man page',
ARRAY[]::text[],
true),

('button_tap_default',
'✅ Button tap received',
'',
'A customer tapped a button on your Middle Man page',
ARRAY[]::text[],
true),

('booking_logged_restaurant',
'🍽️ Reservation logged',
'',
'A reservation has been added',
ARRAY[]::text[],
true),

('booking_logged_barber',
'💇 Booking logged',
'',
'A booking has been added',
ARRAY[]::text[],
true),

('booking_logged_default',
'✅ Booking logged',
'',
'A booking has been added',
ARRAY[]::text[],
true),

('error_alert',
'⚠️ CallMagnet — {{FUNCTION_NAME}} failed',
'<p style="color:#FFFFFF;"><strong>Function:</strong> {{FUNCTION_NAME}}<br><strong>Error:</strong> {{ERROR_MESSAGE}}<br><strong>Time:</strong> {{TIME}}</p>',
'{{FUNCTION_NAME}} errored — check Supabase logs',
ARRAY['FUNCTION_NAME','ERROR_MESSAGE','TIME'],
false),

('expiry_admin_alert',
'[CallMagnet] Free period ending soon — {{BUSINESS_NAME}}',
'<p style="color:#FFFFFF;">{{BUSINESS_NAME}} free period ends on {{END_DATE}}.</p>',
'{{BUSINESS_NAME}} free period ends in 3 days',
ARRAY['BUSINESS_NAME','END_DATE'],
false),

('sms_usage_alert',
'[CallMagnet] SMS usage alert — {{BUSINESS_NAME}}',
'<p style="color:#FFFFFF;">{{BUSINESS_NAME}} has used {{SMS_COUNT}}/{{SMS_INCLUDED}} SMS this month.</p>',
'{{BUSINESS_NAME}} approaching SMS limit',
ARRAY['BUSINESS_NAME','SMS_COUNT'],
false),

('monthly_report_summary',
'[monthly-report] {{PERIOD}}: {{SENT}} sent',
'<p style="color:#FFFFFF;">Monthly report {{PERIOD}}: {{SENT}} sent, {{SKIPPED}} skipped, {{FAILED}} failed.</p>',
'Monthly report complete',
ARRAY[]::text[],
false),

('carl_new_client_alert',
'New client paid — ready to build',
'',
'New client payment received',
ARRAY[]::text[],
false);
