-- unsubscribe_infrastructure: Stage 1 of the opt-out system.
--
-- DORMANT UNTIL PHASE 2. These tables are created now so the data layer is
-- ready before the unsubscribe page and SMS link modifications go live.
-- No existing flows read or write these tables yet.
--
-- Tables created:
--   public.opt_outs            — canonical opt-out state per (client_id, phone)
--   public.unsubscribe_events  — immutable audit log of every opt-out action
--   public.unsubscribe_tokens  — short-lived JWT-less tokens embedded in SMS links
--
-- RLS:
--   opt_outs          — authenticated SELECT for own rows; all writes service_role only
--   unsubscribe_events — service_role only (no client-facing read; privacy-preserving)
--   unsubscribe_tokens — service_role only (prevents token enumeration)

-- ── 1. public.opt_outs ───────────────────────────────────────────────────────
--
-- One row per (client_id, phone_number) pair. UPSERT on conflict so a second
-- opt-out for the same number overwrites rather than duplicates.

CREATE TABLE IF NOT EXISTS public.opt_outs (
  id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id     uuid        NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  phone_number  text        NOT NULL,
  opted_out_at  timestamptz NOT NULL DEFAULT now(),
  permanence    text        NOT NULL
    CONSTRAINT opt_outs_permanence_check
    CHECK (permanence IN ('until_next_call', 'forever')),
  reset_count   integer     NOT NULL DEFAULT 0,
  created_at    timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT opt_outs_client_phone_unique UNIQUE (client_id, phone_number)
);

COMMENT ON TABLE public.opt_outs IS
  'Dormant until Phase 2. Canonical opt-out state per (client_id, phone_number). '
  'Upsert on conflict — one row per pair. reset_count increments each time a '
  'until_next_call opt-out is cleared by a new missed call.';

-- ── 2. public.unsubscribe_events ────────────────────────────────────────────
--
-- Append-only audit log. Never UPDATE or DELETE rows here — any reset is
-- recorded as a new reset_by_new_call event, not a deletion.

CREATE TABLE IF NOT EXISTS public.unsubscribe_events (
  id                 uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id          uuid        NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  phone_number_hash  text        NOT NULL,   -- SHA-256 hex of E.164 phone number
  event_type         text        NOT NULL
    CONSTRAINT unsubscribe_events_event_type_check
    CHECK (event_type IN (
      'link_tapped',
      'confirmed_until_next_call',
      'confirmed_forever',
      'reset_by_new_call',
      'admin_removed'
    )),
  token              text,                   -- nullable; present for link_tapped + confirmed_*
  came_from          text
    CONSTRAINT unsubscribe_events_came_from_check
    CHECK (came_from IN ('sms', 'middle_man', 'admin') OR came_from IS NULL),
  user_agent         text,
  referrer           text,
  time_to_decide_ms  integer,               -- ms from link_tapped → confirmed_*
  occurred_at        timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.unsubscribe_events IS
  'Dormant until Phase 2. Immutable audit log — never UPDATE or DELETE rows. '
  'phone_number_hash is SHA-256(E.164 phone) for privacy. '
  'time_to_decide_ms is null for non-interactive events (reset_by_new_call, admin_removed).';

-- ── 3. public.unsubscribe_tokens ────────────────────────────────────────────
--
-- Short-lived opaque tokens embedded in the SMS unsubscribe link.
-- Token is a random UUID (or random string) generated by the edge function
-- that sends the SMS. expires_at is typically 72 h after creation.

CREATE TABLE IF NOT EXISTS public.unsubscribe_tokens (
  id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  token        text        NOT NULL CONSTRAINT unsubscribe_tokens_token_unique UNIQUE,
  client_id    uuid        NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  phone_number text        NOT NULL,
  created_at   timestamptz NOT NULL DEFAULT now(),
  expires_at   timestamptz NOT NULL,
  used_at      timestamptz             -- null = unused; non-null = already consumed
);

COMMENT ON TABLE public.unsubscribe_tokens IS
  'Dormant until Phase 2. Short-lived opaque tokens embedded in SMS unsubscribe links. '
  'expires_at enforced by process-unsubscribe edge function (typically now()+72h). '
  'used_at is set to now() when the token is consumed — prevents replay attacks.';

-- ── 4. Indexes ────────────────────────────────────────────────────────────────

-- opt_outs: primary lookup path (client + phone)
CREATE INDEX IF NOT EXISTS idx_opt_outs_client_phone
  ON public.opt_outs(client_id, phone_number);

-- opt_outs: find all permanent opt-outs for a client quickly
CREATE INDEX IF NOT EXISTS idx_opt_outs_permanence
  ON public.opt_outs(client_id, permanence);

-- unsubscribe_events: per-client event feed
CREATE INDEX IF NOT EXISTS idx_unsubscribe_events_client_id
  ON public.unsubscribe_events(client_id);

-- unsubscribe_events: time-series queries
CREATE INDEX IF NOT EXISTS idx_unsubscribe_events_occurred_at
  ON public.unsubscribe_events(occurred_at DESC);

-- unsubscribe_tokens: token lookup (the hot path in process-unsubscribe)
CREATE INDEX IF NOT EXISTS idx_unsubscribe_tokens_token
  ON public.unsubscribe_tokens(token);

-- unsubscribe_tokens: expiry pruning queries
CREATE INDEX IF NOT EXISTS idx_unsubscribe_tokens_expires_at
  ON public.unsubscribe_tokens(expires_at);

-- ── 5. Enable RLS ────────────────────────────────────────────────────────────

ALTER TABLE public.opt_outs           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.unsubscribe_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.unsubscribe_tokens ENABLE ROW LEVEL SECURITY;

-- ── 6. RLS policies ──────────────────────────────────────────────────────────
--
-- opt_outs: authenticated clients can SELECT their own rows.
--   INSERT / UPDATE / DELETE: no policy → default-deny for all non-service_role.
--   Edge functions use service_role and bypass RLS entirely.

DROP POLICY IF EXISTS "Clients see own opt_outs" ON public.opt_outs;

CREATE POLICY "Clients see own opt_outs"
  ON public.opt_outs
  FOR SELECT
  TO authenticated
  USING (
    client_id IN (
      SELECT id FROM public.clients WHERE email = auth.jwt() ->> 'email'
    )
  );

-- unsubscribe_events: no policies → service_role only.
-- (Phone hashes still present; restrict to ops access only.)

-- unsubscribe_tokens: no policies → service_role only.
-- (Token values must not be enumerable by clients.)
